# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import web_med.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_med', '0002_auto_20171128_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=web_med.models.get_upload_to),
        ),
    ]
