# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_med', '0004_auto_20171229_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photopng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_photos_png', to='web_med.Patient')),
            ],
        ),
    ]
