# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_med', '0007_auto_20180119_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='web_med.Patient'),
        ),
    ]
