# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_med', '0008_userprofile_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='patient',
        ),
    ]
