# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import web_med.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_med', '0012_auto_20180310_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=web_med.models.get_upload_to_nii)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_niis', to='web_med.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='VTK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=web_med.models.get_upload_to_vtk)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_vtks', to='web_med.Patient')),
            ],
        ),
    ]
